### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by disktnk** [sensorbee/sensorbee-iotop#1]
- [ ] fix each header name (currently temporally name)
- [ ] write each value description on a document
- [ ] add "processing time" on box node
- [ ] add select statement on box node
- [ ] change in/out unit to [tuples/sec], current is counting total tuples
- [ ] support to change interval in running
- [ ] support to change sort key, both command option and in running
- [x] run with a particular topology

**Comment by disktnk** [comment]
these list is moved to projects and this issue is closed.
